import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library, config } from '@fortawesome/fontawesome-svg-core';
import {
  faCircleUser,
  faClock,
  faArrowRotateRight,
  faCheck,
  faArrowUpRightFromSquare,
  faCartShopping,
  faBasketShopping,
  faBell,
  faMagnifyingGlass,
  faSearch,
  faTimes,
  faBars,
  faChevronDown,
  faBatteryFull,
  faDollarSign,
  faMemory,
  faFilter,
  faCompactDisc,
  faMicrochip,
  faBoltLightning,
  faCircleCheck,
  faStopwatch,
  faCamera,
  faCalendar,
  faCalendarDays,
  faLocation,
  faLocationDot,
  faMap,
  faCircle,
  faXmark,
  faCreditCard,
  faEnvelope,
  faPhone,
  faChevronLeft,
  faChevronRight,
  faGears,
  faHome,
  faChevronUp,
  faPen,
  faRightFromBracket,
  faImage,
  faTrash,
  faCrop,
  faRotateRight,
  faFloppyDisk,
  faStar,
  faStarHalfAlt,
  faCircleXmark,
  faPaperPlane,
  faThumbsUp,
  faThumbsDown,
  faReply,
  faCodeCompare,
  faUpDownLeftRight
} from '@fortawesome/free-solid-svg-icons';
import { faCircleQuestion } from '@fortawesome/free-regular-svg-icons';
import { faCcVisa, faGithub, faTwitter } from '@fortawesome/free-brands-svg-icons';

library.add(
  faGithub,
  faTwitter,
  faCircleUser,
  faClock,
  faArrowRotateRight,
  faRotateRight,
  faCheck,
  faArrowUpRightFromSquare,
  faCartShopping,
  faBasketShopping,
  faBell,
  faMagnifyingGlass,
  faSearch,
  faTimes,
  faBars,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faBatteryFull,
  faDollarSign,
  faMemory,
  faFilter,
  faCompactDisc,
  faMicrochip,
  faBoltLightning,
  faCircleCheck,
  faStopwatch,
  faCamera,
  faCalendarDays,
  faLocationDot,
  faMap,
  faCircle,
  faXmark,
  faCreditCard,
  faEnvelope,
  faPhone,
  faGears,
  faHome,
  faPen,
  faRightFromBracket,
  faImage,
  faTrash,
  faCrop,
  faFloppyDisk,
  faCcVisa,
  faStar,
  faStarHalfAlt,
  faCircleXmark,
  faPaperPlane,
  faThumbsUp,
  faThumbsDown,
  faReply,
  faCodeCompare,
  faCircleQuestion,
  faUpDownLeftRight
);

// This is important, we are going to let Nuxt worry about the CSS
config.autoAddCss = false;

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.component('font-awesome', FontAwesomeIcon);
});
